### ISSUE TITLE
No counting bloom filter

### ISSUE THREAD

**Issue by mccoy** [RedisLabsModules/rebloom#18] opened 2017-11-01 12:57 UTC
The old redabloom module provided counting bloom filters, but rebloom does not.  Is this something that is likely to get fixed or are counting filters not on anyone's roadmap for rebloom?

**Comment by dvirsky** [comment] 2017-11-01 13:12
It's not on the road map at the moment, we chose the most basic, compact and fast scalable filter. You can use the old filter, although it's much slower. I'm leaving this open, if enough people will ask for it we'll get to it eventually. If you want to implement it yourself we can help guide you.

**Comment by mccoy** [comment] 2017-11-01 13:15
Thanks for the update.  It is not critical for me at the moment as I can rebuild the filter on a timer to clear removed set members, but in a couple of months it might be worth the effort for me to poke around in the code.

**Comment by dvirsky** [comment] 2017-11-01 13:18
Cool. What we've seen other users do is use different keys per time windows to achieve rolling filters by time frame. It doesn't work for every use case of course.

**Comment by Psli** [comment] 2017-11-19 08:08
+1

**Comment by robwil** [comment] 2017-11-30 16:07
+1

**Comment by casidiablo** [comment] 2017-12-19 00:06
+1

**Comment by mnunberg** [comment] 2017-12-19 00:13
This is in the roadmap for the future - within the next few weeks.

Note that initially it may not have the same level of performance as the current 'normal' bloom filters - and will most likely take the code from the previous redablooms implementation and unify it under a single API.

**Comment by mnunberg** [comment] 2017-12-21 14:00
So I have a few options here:

1. Cuckoo Filter - this might be a somewhat complex implementation but seems to be the most preferred for a 'removable' probabilistic filter
2. Counting bloom filter - this is the traditional counting bloom filter. The problem is that it cannot be scaled beyond its original size. There is also a variable-increment CBF which does the same thing, but is more space efficient. It is still not scalable, though.
3. DaBloom filter. This was used in the old `redablooms` module, but it requires to be used alongside a "numeric ID". This means that you must know this numeric ID in order to save the item as well as remove it (but not check it).

We *could* implement all of them of course, but I want to know what our users would find the most useful. My gut feeling is to say DaBloom because it's been used before, but I really dislike the rules about adding/removing requiring an ID.

**Comment by mnunberg** [comment] 2017-12-21 14:13
@itamarhaber @dvirsky any thoughts on this? ^

**Comment by itamarhaber** [comment] 2017-12-21 14:23
My 2c:

3. The DaBloom was my 3rd module and I basically raped the original lib to ride over the String DMA. While I really enjoyed making up ways to make the ID less painful, it is definitely still a PITA in most cases if not just plain unintuitive.
2. I agree that CBF's unscaliness is disagreeable and definitely not Redis-ish
1. The 2nd module I tried writing (didn't publish though) was a Cuckoo Filter - looked promising and simple both in terms of implementation as well as the public API.

My gut says go cuckoo, either as an addition to rebloom or as a separate module, and between these two I feel most use cases will be covered.

**Comment by mnunberg** [comment] 2017-12-21 23:29
Unfortunately it doesn't seem that cuckoo filters support expansion either. Cuckoo *hashes* support expansion, but not cuckoo filters. They have the same scalability issues as counting bloom filters.

**Comment by mnunberg** [comment] 2017-12-23 01:41
So, it seems there's a solution here and I'm not sure why I hadn't thought of this before: https://cis.temple.edu/~wu/research/publications/Publication_files/Chen_ICNP_2017.pdf

**Comment by mnunberg** [comment] 2017-12-23 17:06
I have a base implementation of only the cuckoo filter itself. It seems to do a pretty good job of auto-expanding so far. I need to benchmark it. Next week I should have an implementation of the filter as a set of Redis commands:

https://github.com/RedisLabsModules/rebloom/tree/cuckoo-filter

**Comment by mnunberg** [comment] 2017-12-25 23:12
This fix is almost ready as a PR. The outstanding items are:

1. Need to test for performance, perhaps additional memory leaks
2. Figure out how to document this (do we want to make this as part of another module, maybe?)
3. Let's agree on the command set. This is fairly straight forward, but let's make sure

**Comment by mnunberg** [comment] 2018-01-02 14:58
The PR has been merged. I'll be revising the API as we go along

**Comment by mnunberg** [comment] 2018-01-03 18:42
API may change slightly, but I believe this can be marked as done.

**Closed by mnunberg** 2018-01-03 18:42 UTC

**Comment by gonedjur** [comment] 2018-03-28 12:24
Nice work on the cuckoo filter! Looks excellent! Was wondering if the qualities of the bloom filters bf.madd would be available with cf.insert i.e. that it would return the exist status in the add?

BF.MADD bloom test
0L (it was present)
cf.insert cuckoo ITEMS test
1L (will return 1L if present or not)

I thought that functionality was kinda nice!
